packages:
  - 'api'
  - 'shared-types'
  - 'web'

allowBuilds:
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  unrs-resolver: true
  sharp: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
